### This notebook deals with all things Binary Classification. Starting with basic NN

In [1]:
import torch
from torch import nn
from torch.nn import functional as F 
from torch import optim

In [2]:
n = torch.randn((1, 4))
n

tensor([[-0.7763, -0.0984, -1.1924,  1.6989]])

In [4]:
sig = nn.Sigmoid()  # the function exists between 0 to 1 like probability, so we use it
sig(n).sum()

tensor(1.8688)

In [13]:
# Defining a simple NN model

class BinClassify(nn.Module):
    def __init__(self, in_features, out_features, hidden_features):
        super(BinClassify, self).__init__()
        self.lin1 = nn.Linear(in_features, hidden_features)  # first layer connected to hidden
        self.relu = nn.ReLU()
        self.lin2 = nn.Linear(hidden_features, out_features)  # hidden to out features
        self.sig = nn.Sigmoid()  # 

    def forward(self, x):
        x = self.lin1(x)
        # print(x)
        x = self.relu(x)
        # print(x)
        x = self.lin2(x)
        # print(x)
        return self.sig(x)
    
bingklassify = BinClassify(4, 1, 10)

In [5]:
from sklearn import datasets

x, y = datasets.make_classification(n_features=4,n_classes=2, n_informative=2, 
                                n_samples=100,)
print(x.shape)
print(y.shape)

(100, 4)
(100,)


In [6]:
y[0:5]

array([1, 0, 0, 1, 0])

In [7]:
from torch.utils.data import DataLoader, Dataset
import numpy as np

class Bingset(Dataset):
    def __init__(self, x, y):
        self.x = torch.from_numpy(x.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.float32))
        self.y = self.y.reshape(-1, 1)
        self.samples = self.x.shape[0]

    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        return self.samples

In [9]:
clas_set = Bingset(x=x, y=y)
clas_set[1]

(tensor([-1.1921, -1.1006, -0.6595,  0.6403]), tensor([0.]))

In [10]:
clas_loader = DataLoader(clas_set, 3)
iter_clas = iter(clas_loader)
next(iter_clas)

[tensor([[-0.1027,  1.9780,  0.4469, -1.7661],
         [-1.1921, -1.1006, -0.6595,  0.6403],
         [ 0.0146, -0.3675, -0.0845,  0.3269]]),
 tensor([[1.],
         [0.],
         [0.]])]

In [16]:
bingklassify(next(iter_clas)[0])

tensor([[0.5770],
        [0.5532],
        [0.5460]], grad_fn=<SigmoidBackward0>)

In [17]:
pred = bingklassify(next(iter_clas)[0])
print("Pred is: ", pred)
print("Actual is:", next(iter_clas)[1])

Pred is:  tensor([[0.5465],
        [0.6297],
        [0.6270]], grad_fn=<SigmoidBackward0>)
Actual is: tensor([[1.],
        [0.],
        [0.]])


In [18]:
fn = nn.CrossEntropyLoss()
pred = bingklassify(next(iter_clas)[0])
loss = fn(pred, next(iter_clas)[1])
loss

tensor(-0., grad_fn=<DivBackward1>)

In [19]:
fn = nn.BCELoss()
pred = bingklassify(next(iter_clas)[0])
loss = fn(pred, next(iter_clas)[1])
loss

tensor(0.6484, grad_fn=<BinaryCrossEntropyBackward0>)

In [20]:
# criterion = nn.CrossEntropyLoss()
fn = nn.BCELoss()  # Binary Cross entropy had to be used.
optimiser = optim.Adam(params=bingklassify.parameters(), lr=0.01)

In [21]:
# 100 pass through the full data using dataloader
for ep in range(100):
    for ind, batch in enumerate(clas_loader):
        # print(batch[0].shape)  # torch.size([3, 4])
        pred_batch  = bingklassify(batch[0])
        loss_cr = fn(pred_batch, batch[1])
        # print(loss_cr.item())
        loss_cr.backward()  # backward pass happens with ease, even though there are multiple elements
        optimiser.step()
        optimiser.zero_grad()
    if ep % 5 == 0:
        print(f"Epoch is {ep} and loss is: {loss_cr.item():.2f}")

Epoch is 0 and loss is: 0.53
Epoch is 5 and loss is: 0.05
Epoch is 10 and loss is: 0.03
Epoch is 15 and loss is: 0.02
Epoch is 20 and loss is: 0.01
Epoch is 25 and loss is: 0.00
Epoch is 30 and loss is: 0.00
Epoch is 35 and loss is: 0.00
Epoch is 40 and loss is: 0.00
Epoch is 45 and loss is: 0.00
Epoch is 50 and loss is: 0.00
Epoch is 55 and loss is: 0.00
Epoch is 60 and loss is: 0.00
Epoch is 65 and loss is: 0.00
Epoch is 70 and loss is: 0.00
Epoch is 75 and loss is: 0.00
Epoch is 80 and loss is: 0.00
Epoch is 85 and loss is: 0.00
Epoch is 90 and loss is: 0.00
Epoch is 95 and loss is: 0.00


In [23]:
with torch.no_grad():
    test_pred = bingklassify(clas_set[10][0])
    print(test_pred)
    print("compared to: ", clas_set[10][1])

tensor([0.0012])
compared to:  tensor([0.])


In [ ]:
# 100 pass through full data using regular tensor
for ep in range(150):
    pred = regmodel(rand_x)
    # print('pred', pred)
    lo = criterion(pred, rand_y)
    # print(lo)
    lo.backward()
    optimiser.step()
    optimiser.zero_grad()
    if ep % 5 == 0:
        print(f"Epoch is {ep} and loss is {lo.item():.3f}")

In [94]:
with torch.no_grad():
    pred = regmodel(rand_x[0])
    print(pred, rand_y[0])

tensor([-5.2124]) tensor([-5.3929])
